site_name: sqCAD
site_description: Superconducting Quantum Circuit Analysis & Design
repo_url: https://github.com/elizabethkunz/sqcad
repo_name: elizabethkunz/sqcad

theme:
  name: material

nav:
  - Home: index.md
  - Install: install.md
  - Quickstart: quickstart.md
  - API: api.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true